# Generated by Django 3.2 on 2022-05-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobopportunities_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopportunities',
            name='posted_date',
        ),
    ]
