# Generated by Django 3.2 on 2022-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobopportunities_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunities',
            name='company_name',
            field=models.CharField(default='', max_length=150, verbose_name='Company Name'),
            preserve_default=False,
        ),
    ]
