# Generated by Django 3.2 on 2022-05-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobopportunities_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopportunities',
            name='user_obj',
        ),
    ]
