# Generated by Django 3.2 on 2022-05-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobopportunities_user_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopportunities',
            name='slug',
        ),
    ]
